@startuml
title Warmhouse Context Diagram

top to bottom direction

!include C4_Context.puml

Person(user, "Пользователь", "Пользуется услугами компании 'Тёплый дом'")
Person(admin, "Специалист", "Сотрудник компании 'Тёплый дом'")

System(system, "Монолитное приложение управления отоплением", "Управление отоплением, мониторинг данных о температуре")

System_Ext(sensor, "Датчики и реле отопления", "Физические устройства, установленные в домах клиентов")

Rel(user, system, "Управляет отоплением, проверяет температуру, оставляет заявку на установку датчиков")
Rel(system, user, "Отправляет статус отопления и текущую температуру")

Rel(system, sensor, "Команды управления отоплением")
Rel(sensor, system, "Отправяет температуру")

Rel(admin, system, "Настройка и подключение датчиков")
@enduml
