openapi: 3.0.3
info:
  title: Auth Service API
  description: API для регистрации, аутентификации и управления доступом пользователей
  version: 1.0.0
servers:
  - url: https://api.warmhouse.com/auth
paths:
  /register:
    post:
      summary: Регистрация нового пользователя
      description: Создаёт профиль пользователя и сохраняет его данные
      requestBody:
        description: Данные для регистрации пользователя
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Ошибка валидации данных
  /login:
    post:
      summary: Аутентификация пользователя
      description: Проверяет логин и пароль, возвращает JWT токен
      requestBody:
        description: Логин и пароль пользователя
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Успешная аутентификация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
        '401':
          description: Неверный логин или пароль
  /token:
    get:
      summary: Получение токена аутентификации
      description: Возвращает JWT токен для авторизованного пользователя
      security:
        - bearerAuth: []
      responses:
        '200':
          description: JWT токен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
        '401':
          description: Неавторизованный доступ

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserRegistration:
      type: object
      required:
        - username
        - password
        - email
      properties:
        username:
          type: string
          example: johndoe
        password:
          type: string
          format: password
          example: strongpassword123
        email:
          type: string
          format: email
          example: john@example.com
    UserLogin:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: johndoe
        password:
          type: string
          format: password
          example: strongpassword123
    UserProfile:
      type: object
      properties:
        userId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        username:
          type: string
          example: johndoe
        email:
          type: string
          format: email
          example: john@example.com
    AuthToken:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
