@startuml
!include <C4/C4_Container>
!include <C4/C4_Context.puml>
!include <C4/C4_Container.puml>
!include <C4/C4_Component.puml>
!include <C4/C4.puml>
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary(smart_home, "Управление умным домом (Smart Home API)") {
  Component(api, "SmartHome REST API", "REST", "Основная точка входа для клиента и других систем")
  Component(device_manager, "Device Manager", "Бизнес-логика", "Добавление/удаление устройств, назначение устройств пользователям")
  Component(device_configurator, "Device Configurator", "Бизнес-логика", "Конфигурирование/настройка параметров подключённых устройств")
  Component(device_event_publisher, "Event Publisher", "Pub/Sub", "Публикация событий об изменениях устройств")
  Component(db_access, "Data Access Layer", "Postgres", "Хранение устройств пользователя и настроек")
}


Rel(api, device_manager, "Запросы на добавление/удаление устройств")
Rel(api, device_configurator, "Запросы на конфигурирование устройств")
Rel(device_manager, db_access, "Сохраняет изменения устройств пользователя")
Rel(device_configurator, db_access, "Сохраняет параметры устройств")
Rel(device_manager, device_event_publisher, "Публикация событий об изменениях состава устройств")
Rel(device_configurator, device_event_publisher, "Публикация событий настройки и статуса")
Rel(device_event_publisher, internal_subscribers, "Публикует события")
@enduml
